export { default as HomeView } from "./HomeView.vue"
export { default as HideView } from "./HideView.vue"
export { default as GenerateView } from "./GenerateView.vue"
export { default as ListView } from "./ListView.vue"
export { default as LoginView } from "./LoginView.vue"
export { default as RegisterView } from "./RegisterView.vue"
